language: python
python:
  - "3.8"

services:
 - postgresql

# command to install dependencies
install: "pip install -r requirements.txt"

env:
  - DATABASE_URI=postgres://postgres:@localhost:5432/test

before_script:
  - psql -c 'create database test;' -U postgres


# command to run tests
script: 
  - nosetests

#after_success:
# - codecov
 
