language: python
python:
  - "3.8"

services:
 - postgresql

# command to install dependencies
install: "pip install -r requirements.txt"

env:
  - DATABASE_URI="postgres://gswncbve:1n4JGHLrb0dVst_PgDrr92DyP87RgOYu@batyr.db.elephantsql.com/gswncbve"

before_script:
  - psql -c 'create database test;' -U postgres


# command to run tests
script: 
  - nosetests

after_success:
 - codecov
 
